- name: Download zshell plugins
  ansible.builtin.command: "{{ item }}"
  loop:
    - git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    - git clone https://github.com/joshskidmore/zsh-fzf-history-search ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-fzf-history-search
    - git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

- name: Ensure directory structure for templates exists
  ansible.builtin.file:
    path: "{{ user_home }}/{{ item.path }}"
    state: directory
  with_filetree: templates/
  when: item.state == 'directory'

- name: Ensure files are populated from templates
  template:
    src: "{{ item.src }}"
    dest: "{{ user_home }}/{{ item.path | dirname }}/{{ item.path | basename | regex_replace('\\.j2$', '') }}"
  with_filetree: templates/
  when: item.state == 'file'

- name: Swap escape and caps lock
  ansible.builtin.command: gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"
- name: Install UNIX tools from apt
  become: true
  ansible.builtin.apt:
    name:
      - bat
      - jq
      - silversearcher-ag
      - tree
      - xz-utils
    update_cache: true
- name: Install UNIX tools from deb packages
  become: true
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop:
    - https://github.com/dandavison/delta/releases/download/0.13.0/git-delta_0.13.0_amd64.deb
