- name: Copy dotfiles into home
  ansible.builtin.template:
    src: "templates/{{ item.src }}"
    dest: "{{ user_home }}/{{ item.dest }}"
  loop:
    - { src: ".zshrc.j2", dest: ".zshrc" }

- name: Create desktop entries
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ user_home }}/.local/share/applications/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_fileglob:
    - ../templates/desktop-entries/*.j2
