- name: Install arch packages
  community.general.pacman:
    name:
      # general
      - yay
      - thunar
      - thunderbird
      - chromium
      - firefox
      - keepassxc
      - nextcloud-client
      - telegram-desktop
      - flameshot
      - filezilla
      - okular
      - libreoffice-fresh
      # programming
      - git
      - alacritty
      - python-pip
      - rustup
      - texlive-science
      - docker
      - docker-compose
      - ttf-hack
      # wayland
      - kanshi
      - wdisplays
      # UNIX tools
      - jq
      - fx
      - xsv
      - bat
      - git-delta
      - tree
    state: present

# # hmm...
# - name: Install packages from AUR
#   ansible.builtin.command:
#     argv:
#       - yay
#       - -Sq
#       - --answerclean
#       - NotInstalled
#       - --answerdiff
#       - None
#       - --sudoloop
#       - --noconfirm
#       - spotify
#       - visual-studio-code-bin
#       - zotero
#       - obsidian
#       - autojump
#       - protonmail-bridge-bin

- name: Install CPAN packages
  community.general.cpanm:
    name: "{{ item }}"
  loop:
    - Log::Log4perl
    - Log::Dispatch
    - YAML::Tiny
    - File::HomeDir

- name: Ensure directory structure for templates exists
  ansible.builtin.file:
    path: "{{ user_home }}/{{ item.path }}"
    state: directory
  with_filetree: templates/
  when: item.state == 'directory'

- name: Ensure files are populated from templates
  template:
    src: "{{ item.src }}"
    dest: "{{ user_home }}/{{ item.path | dirname }}/{{ item.path | basename | regex_replace('\\.j2$', '') }}"
  with_filetree: templates/
  when: item.state == 'file'
